---
title: "Restaurant"
author: "PoMingChen"
date: "2019/3/16"
output: html_document
---

```{r}
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Muslin

```{r}
library(readr);library(jsonlite);library(xml2);
# library(xmltools);
library(stringr);library(dplyr);library(lubridate)

# devtools::install_github('ultinomics/xmltools')
# library(xmltools)
```

```{r}
read_csv("./Muslin_friend/china.csv") -> MuslinRestbyChina
read_csv("./Muslin_friend/kao.csv") -> MuslinRestbyKao
read.csv("./Muslin_friend/taipei.csv") -> MuslinRestTaipei
read.csv("./Muslin_friend/taiwan.csv") -> MuslinRestTaiwan
```

```{r}

MuslinRestbyChina$序<-NULL
MuslinRestbyChina$認證別<-NULL
MuslinRestbyChina$認證單位<-NULL
MuslinRestbyChina$備註<-NULL

MuslinRestbyKao$序<-NULL
MuslinRestbyKao$認證別<-NULL
MuslinRestbyKao$認證單位<-NULL
MuslinRestbyKao$備註<-NULL

MuslinRestTaipei$序<-NULL
MuslinRestTaipei$認證別<-NULL
MuslinRestTaipei$認證單位<-NULL
MuslinRestTaipei$備註<-NULL

MuslinRestTaiwan$序<-NULL
MuslinRestTaiwan$認證別<-NULL
MuslinRestTaiwan$認證單位<-NULL
MuslinRestTaiwan$備註<-NULL

```

```{r}
MuslinRestbyChina %>%
  mutate(
    英文地址 = str_extract(地址,"(?<=([:blank:]|\\)|\\,))([:alpha:]|[:digit:]|[:punct:]|[:space:])+"),
    地址 = str_remove(地址,"(?<=([:blank:]|\\)|\\,))([:alpha:]|[:digit:]|[:punct:]|[:space:])+")
  ) -> MuslinRestbyChina

```

```{r}
MuslinRestbyKao %>%
  mutate(
    英文地址 = str_extract(地址,"(?<=(號))([:alpha:]|[:digit:]|[:punct:]|[:space:])+"),
    地址 = str_remove(地址,"(?<=(號))([:alpha:]|[:digit:]|[:punct:]|[:space:])+")
  ) ->MuslinRestbyKao
```

<<<<<<< HEAD
#MuslinRestbyChina$地址 %>%
#  str_remove("(?<=[:blank:])([:alpha:]|[:digit:]|[:punct:]|[:space:])+") #->MuslinRestbyChina$地址

MuslinRestbyChina
=======
```{r}
MuslinRestTaipei %>%
  mutate(
    英文地址 = str_extract(地址,"(?<=[:blank:])([:alpha:]|[:digit:]|[:punct:]|[:space:])+"),
    地址 = str_remove(地址,"(?<=[:blank:])([:alpha:]|[:digit:]|[:punct:]|[:space:])+")
  ) -> MuslinRestTaipei
```

```{r}
MuslinRestTaiwan %>%
  mutate(
    英文地址 = str_extract(地址,"(?<=(號))([:alpha:]|[:digit:]|[:punct:]|[:space:])+"),
    地址 = str_remove(地址,"(?<=(號))([:alpha:]|[:digit:]|[:punct:]|[:space:])+")
  ) -> MuslinRestTaiwan
>>>>>>> 98cf3c889307886a5058c2ecd31c0b5023263392
```


### Vegetarian
```{r}
# read_csv("vegeterian_friend/manifest.csv")
read_csv("vegeterian_friend/中文版.csv") -> vegeChinese
read_csv("vegeterian_friend/日文版.csv") -> vegeJapanese
read_csv("vegeterian_friend/韓文版.csv") -> vegeKorean
read_csv("vegeterian_friend/英文版.csv") -> vegeEnglish

vegeChinese %>% select(座標位置)
```

```{r}
vegeChinese$座標位置 %>% 
  str_extract("(?<=(\\,))([:digit:]|\\.)+") %>% 
  as.numeric-> vegeChinese$經度

vegeChinese$座標位置 %>% 
  str_remove("(?<=(\\,))([:digit:]|\\.)+") ->vegeChinese$座標位置

vegeChinese %>%
  rename( 緯度 = 座標位置) ->vegeChinese
vegeChinese$緯度 %>%
  str_extract("([:digit:]|\\.)+(?=(\\,))") %>%
  as.numeric ->vegeChinese$緯度
```

```{r}
vegeChinese %>%
  select(客戶名稱,緯度,經度) -> VegeCoordinate
```

```{r}
save(vegeChinese,vegeEnglish,vegeJapanese,vegeKorean,VegeCoordinate,file = "restaurant.RData")
```

